### ISSUE TITLE
[Install Error] cannot find -lblas

### ISSUE THREAD

**Issue by silvewheat** [bcm-uga/Loter#13]
Hello,
      I tried to install in linux system, but an error occurred as below (the last three lines):

> /usr/bin/ld: cannot find -lblas
> collect2: error: ld returned 1 exit status
> error: command 'g++' failed with exit status 

Is there something I need to install as a dependency?

**Comment by ntm** [comment]
you need to install the blas library, eg on centos or fedora:
yum install blas

**Comment by gdurif** [comment]
Hi,
Thanks @ntm for the answer. On debian and derivatives (ubuntu, etc.), you can do:
```
apt-get install libblas-dev
```
