### ISSUE TITLE
no reference in test data

### ISSUE THREAD

**Issue by liufy11** [bcm-uga/Loter#14]
I run loter with the command "loter_cli data/H_ceu.npy data/H_yri.npy -a data/H_mex.npy -f npy -o tmp.npy -n 8 -v"
The screen says : loter_cli: error: argument -r/--ref is required
but there's no reference in data.

**Comment by gdurif** [comment]
There is a typo in the README file, you should use
```bash
loter_cli -r data/H_ceu.npy data/H_yri.npy -a data/H_mex.npy -f npy -o tmp.npy -n 8 -v
```

**Comment by liufy11** [comment]
I get the file named tmp.npy, but I do not know what does the numbers in tmp.npy mean. and It seems tmp.py is not the final file, so what should I do next ?------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;gdurif&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月9日(星期二) 下午4:51
收件人:&nbsp;&quot;bcm-uga/Loter&quot;<Loter@noreply.github.com&gt;;
抄送:&nbsp;&quot;liufy11&quot;<365698105@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bcm-uga/Loter] no reference in test data (#14)
