### ISSUE TITLE
How to get the introgressed segment

### ISSUE THREAD

**Issue by silvewheat** [bcm-uga/Loter#17]
Hi, I used the lc.loter_smooth to get the result. But the result is the classification of each single SNPs. How I can get the introgressed regions? By merging the consecutive SNPs belong to a same source? And how much exception (SNPs belong to another souce) we can tolerate to extend the introgressed segment?

Best wishes,
Yudong

**Comment by gdurif** [comment]
Hi,

Loter gives you the ancestral origin at the SNP scale, but the algorithm does not consider SNPs independently, so chunks of consecutive SNPs from the same ancestral origin corresponds to introgressed regions.

`lc.loter_smooth` implements a smoothing step after the Loter core algorithm to correct for these exceptions that you mention, so you should be able to directly use the painting given in the output.

Obviously, there could be some errors in the inferred ancestry, Loter performance review (see [1]) shows that Loter results are very trustworthy when investigating recent admixture events. For older admixture events, the performance are quite good (up to the state-of-the-art) but you get more errors (as with any other local ancestry inference method).

Do not hesitate if you have further questions.
Best,

[1] https://academic.oup.com/mbe/article/35/9/2318/5040668

**Comment by silvewheat** [comment]
Thanks so much for your careful and swiftly reply!

Best wishes,
Yudong
