### ISSUE TITLE
Output haplotype order

### ISSUE THREAD

**Issue by gaushi** [bcm-uga/Loter#2]
Hi Michael,
I needed some clarification on how the output haplotypes are ordered. 
The manual says:
"Finally, we can save the result. Each line correspond to an haplotype. The SNPs are space delimited"

Do the haplotypes follow order(two per individual, for diploid organism) exactly similar to the input vcf file?

Thanks a lot,
With best regards,
Gautam

**Comment by mblumuga** [comment]
Yes, haplotypes follow order(two per individual, for diploid organism) exactly similar to the input vcf file. Sorry for the slow reply.
Michael

**Comment by meddly** [comment]
Hello Michael,
I obtained the results for one admixed individual of two parental populations. I have some questions regarding how to interpret the output. 
1- Each color represents one parental, right? May I know which color corresponds to which parental? (code: res_loter = lc.loter_smooth(l_H=[parent1_hap, parent2_hap], h_adm=amx_hap, num_threads=8)
![loter_chunks_tryp](https://user-images.githubusercontent.com/9641919/48835564-93b00180-ed67-11e8-9fe3-c96dc5400b03.png)

2- In the output text. Each par of numbers represent the ancestry of the two allels of each SNP?. I would like to know which is the ancestry of each SNP or of a set of SNPs from my VCF. How can I obtaine that data from the txt file?
![image](https://user-images.githubusercontent.com/9641919/48835896-7f203900-ed68-11e8-9aff-d3e5c7c47e4f.png)

Best regards, 
Meddly

**Comment by ana090192** [comment]
Hi, 
Could someone send me a link to the Loter manual? Is there a PDF version? 

Thanks a lot,
Best,
Ana

**Comment by gdurif** [comment]
Hi Ana, here is the link to the Python notebook explaining how to use Loter (https://github.com/bcm-uga/Loter/blob/master/python-package/Local_Ancestry_Example.ipynb), there is no pdf version for the moment.
Best

**Comment by ana090192** [comment]
Hi,
Thank you very much!
Best
