### ISSUE TITLE
Plotting of output 

### ISSUE THREAD

**Issue by DEYANGEIOZ** [bcm-uga/Loter#23]
Hi,
Thank you very much for your great contribution on this. 
Is there a simple way to plot the result in R, and to generate vector files that could be compiled in the following step? 
I found it is different from the common heatmap structure. 
Thank you.  
Deyan

**Comment by gdurif** [comment]
Hi,
Could give me more details about what you want to do with the results ? You could use the option `-f txt` for `loter_cli` which will produce a text data file with individuals in rows and inferred ancestry in columns. Then, you can load this result file within R (e.f. with `read.table`) and plot the result in R with
```R
res <- read.table(...)
heatmap(res, Rowv = NA, Colv = NA, scale = "none")
```
Do not hesitate if you have any further question.
Best
