### ISSUE TITLE
Unsinstall package

### ISSUE THREAD

**Issue by meddly** [bcm-uga/Loter#4]
Hello  Michael, 
I would like to install the new version of Loter package. Is there any specific procedure that I should follow to? Or I can just drop the folder?. Thank you

**Comment by gdurif** [comment]
Hi, if you already have cloned the repository once, you can do:

```
cd Loter
git pull origin master
rm -rf build dist # maybe not necessary
python setup.py install
```

Or you can just clone the repository and follow the instruction as you did before.
