### ISSUE TITLE
Error in loter_smooth

### ISSUE THREAD

**Issue by meddly** [bcm-uga/Loter#5]
Hello, After I run this code of the example:
>>>res_loter = lc.loter_smooth(l_H=[ceu_hap, yri_hap], h_adm=mex_hap, num_threads=8) 
>>>**print(res_loter.shape)** 
I obtained this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I/O operation on closed file.

Thank you

**Comment by gdurif** [comment]
Closed because no news
