### ISSUE TITLE
help for chloroplast genomes

### ISSUE THREAD

**Issue by Mirror361025** [bcm-uga/Loter#8]
Hi. I am Eda. Recently, I wanna detect the heteroplasmy and Infer Local Ancestry among 16 populations of 27 different species based on cp genomes. Could I use Loter to conduct these analyses for chloroplast genomes????

**Comment by Mirror361025** [comment]
or it just can be used for nuclear genomes?

**Comment by gdurif** [comment]
I am not familiar with the specificity of chloroplast genomes, however if you have haplotypes data (0-1 SNP tables) for admixed individuals and for individuals from different reference population, I don't see why Loter would not work.

Indeed, our method is purely computational (least square criterion with a penalty on the jump form a reference to another) and does not implement any specific biological assumptions.

**Comment by mblumuga** [comment]
> or it just can be used for nuclear genomes?

No, it handles haplotypic data and cp genomes should be fine. Even  with diploid data, loter expects phased haplotypes.

**Comment by Mirror361025** [comment]
thanks
